name: Post updated articles to X

on:
  push:
    paths:
      - "articles/*.md"  # articlesディレクトリ内の.mdファイルの変更をトリガー

jobs:
  post_to_x:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # 直近の2つのコミットを取得して差分を比較

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests requests-oauthlib

      - name: Extract titles, URLs, and topics from updated articles
        id: extract_posts
        run: |
          UPDATED_FILES=$(git diff --name-only HEAD^ HEAD | grep '^articles/.*\.md')
          
          for FILE in $UPDATED_FILES; do
            # ファイル名から拡張子.mdを除去してpage-titleを生成
            PAGE_TITLE=$(basename "$FILE" .md)
            URL="${{ secrets.BASE_URL }}/$PAGE_TITLE"
            
            # titleのフィールドを抽出
            TITLE=$(grep '^title:' "$FILE" | sed 's/title: "\(.*\)"/\1/')

            # topicsのフィールドを抽出
            TOPICS=$(grep '^topics:' "$FILE" | sed 's/topics: \[\(.*\)\]/\1/' | sed 's/"//g')

            # 投稿内容とURL、トピックを環境変数に設定
            echo "TWEET_CONTENT_$PAGE_TITLE=${TITLE}という記事を作成しました！" >> $GITHUB_ENV
            echo "URL_$PAGE_TITLE=$URL" >> $GITHUB_ENV
            echo "TOPICS_$PAGE_TITLE=$TOPICS" >> $GITHUB_ENV
          done

      - name: Run Python script to post to X
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python post_to_x.py
