name: Post updated articles to X

on:
  push:
    paths:
      - "articles/*.md"  # articlesディレクトリ内の.mdファイルの変更をトリガー

jobs:
  post_to_x:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # 直近の2つのコミットをフェッチして差分を比較できるようにする

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests requests-oauthlib

      - name: Extract titles and URLs from updated articles
        id: extract_posts
        run: |
          # articlesディレクトリ内で変更された.mdファイルのリストを取得
          UPDATED_FILES=$(git diff --name-only HEAD^ HEAD | grep '^articles/.*\.md')
          
          # 各ファイルに対してタイトルとリンクを抽出
          for FILE in $UPDATED_FILES; do
            # ファイル名から拡張子.mdを除去してpage-titleを生成
            PAGE_TITLE=$(basename "$FILE" .md)
            URL="${{ secrets.BASE_URL }}/$PAGE_TITLE"
            
            # titleのフィールドを抽出
            TITLE=$(grep '^title:' "$FILE" | sed 's/title: "\(.*\)"/\1/')

            # 投稿内容のフォーマット
            TWEET_CONTENT="${TITLE}という記事を作成しました！\n${URL}"

            # 各投稿内容を保存（エクスポート）
            echo "TWEET_CONTENT_$PAGE_TITLE=$TWEET_CONTENT" >> $GITHUB_ENV
          done

      - name: Run Python script to post to X
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python post_to_x.py
